### PR TITLE
Health system

### PR DESCRIPTION
**Pull request by perryhq**
Added the `HealthSystem` class, a `MonoBehaviour` that deals with health, and has methods and events to help using it

### CODE REVIEW

**Comment by perryhq** [comment]
Sorry for the requests, github mobile wasn't cooperating

**Comment by perryhq** [comment]
I'm so dumb, I'm reversing this commit when I get free time

**Comment by perryhq** [comment]
I'm going to repopen it when it's actually ready

**Comment by sadkris** [comment]
thanks bb

**Pull request closed without merging**
