### PR TITLE
Patching Stealth Bot

### PR DESCRIPTION
**Pull request by sadkris**

### CODE REVIEW

**Comment by sadkris** [comment]
buh

**Comment by perryhq** [comment]
I think I fixed the merge conflicts but there's a chance I messed up but everything seems to be working fine.

**Comment by perryhq** [comment]
Pressed the button on accident

**Comment by perryhq** [comment]
I can review the pr but I made some things, so would it count as bias?

**Comment by sadkris** [comment]
The entire point of this PR is to move the files to the proper folder, and you just moved them out of it.

**Comment by perryhq** [comment]
Weird I didn't move them.

I literally just ran the character creator again and rebaked the navmesh.

**Comment by perryhq** [comment]
The error was me trying to fix the merge conflicts. I will move them to the correct place when I get free time.

**Pull request merged**
