### PR TITLE
Initial Commit ABILITY_TPS_Crouch

### PR DESCRIPTION
**Pull request by tobar-io**
Hi Luke! Fun stuff! Hope you like it :)

Devlog: https://www.tobar.io/devlog-feature-ability_crouch/

Attention:

- I made a separate Animator
- Animations are from Mixamo
- I hijacked the Demo Scene to show off the tunnel Detection Overwritten the player Prefab of course
- Camera height (root) gets changed on Crouch. It feels a bit unsafe. Maybe it's an idea to couple the root to the Skeleton, so it follows the movement automatically.
- Autocrouch Detection is on "Default" Layer because I dont wanted to create an extra Layer in the project. It still works, though ;)

Features

- The crouching ability can be triggered by toggling or holding
- An “over-the-shoulder” cinemachine camera gets activated, as soon as the view gets narrower (I'm using the thirdpersonaim Camera)
- The player will only stand up if there is enough headroom, to reduce clipping
- The component will detect if there is a space in walking direction where crouching is possible
 - On detection the component will automatically call "Crouch()", if enabled

### CODE REVIEW

**Comment by tobar-io** [comment]
Bug: The SprintStamina depletes on crouch, when pressing the sprint-key.

**Comment by sadkris** [comment]
I don't know what Etra will say about the Mixamo animations, but otherwise it looks very well done. The only thing we may change past bug fixing is making our own animation for crouching.

**Comment by sadkris** [comment]
Also, feel free to join the community and development discord. The link for the latter is in the "volunteer" channel of the community server, which is linked in the README and the assets.

**Comment by tobar-io** [comment]
> I don't know what Etra will say about the Mixamo animations, but otherwise it looks very well done. The only thing we may change past bug fixing is making our own animation for crouching.

Thank you.

Yes. I told Etra, that I tried to find open source animations, but wasnt succesful. I'm not the best animator, but maybe I can do something half useful with umotion pro.

> Also, feel free to join the community and development discord. The link for the latter is in the "volunteer" channel of the community server, which is linked in the README and the assets.

I was invited to the Channel by Etra but not I'm yet verified or something.

**Comment by sadkris** [comment]
Hey! From testing it using the default armature in the No Character Demo, I found a couple issues I'll need you to address. The big one is that the controller isn't properly detecting the tunnel as a physical object in the demo, and is as such letting you stand up in the middle of it, clipping the character into the ceiling. As well as this, when leaving a surface you're clipped into, it adds a very large sum of velocity in the direction you left it at. If you can get this bug fixed and produce me with a short demo of it working with the obstacle in question using your animations, I can put it under review again and sign off on it

**Comment by sadkris** [comment]
Don't mind my silliness, I just realized you hijacked the TPS demo for it. Still should be brought to your attention that it doesn't work properly out of the box from making a new character controller and adding the ability, as described before

**Comment by tobar-io** [comment]
Hi, the layer masks should be set to the layer the tunnel has, maybe we should set it to default by default. The propelling out of the tunnel behaviour happens when the character controller size changes and collides with the tunnel roof. This should also not happen when the collider masks are set. To make it work out of the box I just can set the defaults in the script. Will fix that.

**Comment by sadkris** [comment]
I'll look into the new commit. For context, the crouching sections there used box colliders to assist with collision. I didn't check how your tunnel was

**Comment by sadkris** [comment]
Yep! Looks good. I'll put on an approval for merging, but we'll probably still need to make new animations for it, so you can run us through how you set it up in the server once Etra lets you in.

**Review by sadkris — COMMENTED** [review]
it good, works fine with box colliders. animations need to be properly implemented

**Comment by sadkris** [comment]
Also, I do need you to push a commit to remove the animation

**Review by sadkris — APPROVED** [review]
No issues, crouching animations to be added in future

**Pull request merged**
