### PR TITLE
Change readme

### PR DESCRIPTION
**Pull request by perryhq**
Just changed the some parts of the readme file so it's more organized and follows better guidelines.

### CODE REVIEW

**Review by sadkris — CHANGES_REQUESTED** [review]
Please change the overview and modding video links with https://youtu.be/5Yb4oaFpZ04 and https://youtu.be/q26z6KW1geI respectively. You linked the old, unlisted versions.

**Comment by perryhq** [comment]
Ok, I just used the links already on the file. Changing it.

**Review by Etra-Games — APPROVED** [review]
Thank you so much perry and Kris!

**Review by Etra-Games — APPROVED** [review]
Thank you so much Kris!

**Pull request merged**
